# Netlify Configuration
[build]
publish = "."

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

# URL Redirects
[[redirects]]
from = "/index.html"
to = "/"
status = 301

[[redirects]]
from = "/blog-list.html"
to = "/blog-list"
status = 301

[[redirects]]
from = "/recruit.html"
to = "/recruit"
status = 301

[[redirects]]
from = "/blog-post-*.html"
to = "/blog-post-:splat"
status = 301

[[redirects]]
from = "https://www.primeasset-realestate.co.kr/*"
to = "https://primeasset-realestate.co.kr/:splat"
status = 301
force = true
